export const STYLE_COLOR_MAP = {
  "Active text": { position: 3, index: 2 },
  "Active window title": { position: 17, index: 16 },
  "Block background": { position: 42, index: 41 },
  "Border": { position: 12, index: 11 },
  "Button": { position: 29, index: 28 },
  "Button active": { position: 30, index: 29 },
  "Button active text": { position: 31, index: 30 },
  "Disabled text": { position: 2, index: 1 },
  "Frame active background": { position: 14, index: 13 },
  "Frame background": { position: 13, index: 12 },
  "Link": { position: 32, index: 31 },
  "Link active": { position: 33, index: 32 },
  "Logo": { position: 6, index: 5 },
  "Logo back": { position: 45, index: 44 },
  "Main window background": { position: 10, index: 9 },
  "Popup background": { position: 9, index: 8 },
  "Preview background": { position: 11, index: 10 },
  "Scrollbar background": { position: 18, index: 17 },
  "Scrollbar grab": { position: 19, index: 18 },
  "Scrollbar grab active": { position: 20, index: 19 },
  "Selection": { position: 35, index: 34 },
  "Separator": { position: 36, index: 35 },
  "Shadows": { position: 40, index: 39 },
  "Sidebar background": { position: 7, index: 6 },
  "Sidebar selection": { position: 43, index: 42 },
  "Sidebar text": { position: 5, index: 4 },
  "Slider active background": { position: 26, index: 25 },
  "Slider background": { position: 25, index: 24 },
  "Slider grab": { position: 27, index: 26 },
  "Slider grab active": { position: 28, index: 27 },
  "Small text": { position: 4, index: 3 },
  "Spinner": { position: 41, index: 40 },
  "Switch": { position: 21, index: 20 },
  "Switch active": { position: 22, index: 21 },
  "Switch active background": { position: 24, index: 23 },
  "Switch background": { position: 23, index: 22 },
  "Tab": { position: 37, index: 36 },
  "Text": { position: 1, index: 0 },
  "Text preview": { position: 15, index: 14 },
  "Text selection": { position: 39, index: 38 },
  "Window title": { position: 16, index: 15 }
} as const;